Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Rails:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false

Style/AlignArray:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  AutoCorrect: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FirstParameterIndentation:
  AutoCorrect: false
Style/GuardClause:
  Enabled: false
Style/IndentArray:
  EnforcedStyle: consistent
Style/IndentHash:
  EnforcedStyle: consistent
Style/LeadingCommentSpace:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/MultilineBlockChain:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - Gemfile
    - lib/history.pb.rb
    - db/migrate/**/*.rb
    - vendor/**/*
    - bin/**/*

